# Generated by Django 2.2 on 2019-06-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-date']},
        ),
    ]
